package com.robrua.orianna.type.game;

public enum SubType {
    ARAM_UNRANKED_5x5, ASCENSION, BOT, BOT_3x3, CAP_5x5, FIRSTBLOOD_1x1, FIRSTBLOOD_2x2, HEXAKILL, NIGHTMARE_BOT, NONE, NORMAL, NORMAL_3x3, ODIN_UNRANKED, ONEFORALL_5x5, RANKED_PREMADE_3x3, RANKED_PREMADE_5x5, RANKED_SOLO_5x5, RANKED_TEAM_3x3, RANKED_TEAM_5x5, SR_6x6, URF, URF_BOT
}
