package com.robrua.orianna.type.core.common;

public enum SubType {
    ARAM_UNRANKED_5x5, ASCENSION, BILGEWATER, BOT, BOT_3x3, CAP_5x5, COUNTER_PICK, FIRSTBLOOD_1x1, FIRSTBLOOD_2x2, HEXAKILL, KING_PORO, NIGHTMARE_BOT, NONE, NORMAL, NORMAL_3x3, ODIN_UNRANKED, ONEFORALL_5x5, RANKED_FLEX_SR, RANKED_SOLO_5x5, RANKED_TEAM_3x3, RANKED_TEAM_5x5, SIEGE, SR_6x6, URF, URF_BOT;
}
