package lib.orianna.type.game;

public enum GameMap {
    CRYSTAL_SCAR, HOWLING_ABYSS, PROVING_GROUNDS, SUMMONERS_RIFT_AUTUMN, SUMMONERS_RIFT_SUMMER, TWISTED_TREELINE, TWISTED_TREELINE_ORIGINAL
}
