package lib.orianna.type.match;

public enum EventType {
    BUILDING_KILL, CHAMPION_KILL, ELITE_MONSTER_KILL, ITEM_DESTROYED, ITEM_PURCHASED, ITEM_SOLD, ITEM_UNDO, SKILL_LEVEL_UP, WARD_KILL, WARD_PLACED;
}
